
export const transactions = [
    {
      id: 1,
      orderId: "SKN1200",
      product: "Watch Nike Series 7",
      customer: "Robert Fox",
      date: "01.01.2024",
      status: "pending",
      totalPrice: "₦399.00",
    },
    {
      id: 2,
      orderId: "SKN1201",
      product: "Watch Nike Series 7",
      customer: "Robert Fox",
      date: "01.01.2024",
      status: "completed",
      totalPrice: "₦399.00",
    },
    {
      id: 3,
      orderId: "SKN1202",
      product: "Watch Nike Series 7",
      customer: "Robert Fox",
      date: "01.01.2024",
      status: "canceled",
      totalPrice: "₦399.00",
    },
    {
      id: 4,
      orderId: "SKN1203",
      product: "Watch Nike Series 7",
      customer: "Robert Fox",
      date: "01.01.2024",
      status: "pending",
      totalPrice: "₦399.00",
    },
    {
      id: 5,
      orderId: "SKN1204",
      product: "Watch Nike Series 7",
      customer: "Robert Fox",
      date: "01.01.2024",
      status: "pending",
      totalPrice: "₦399.00",
    },
  ];